import { projectSessions, type Finding, type McpSummary, type SessionSummary, type SkillDoctorSummary, type TaskSummary, type ToolCall, type VeyrEvent } from '@veyr/core';

export interface ReportData { generatedAt: string; events: VeyrEvent[]; findings: Finding[]; tasks: TaskSummary[]; skillDoctor: SkillDoctorSummary; }
export type ReportLanguage = 'zh-CN' | 'en';

const copy = {
  'zh-CN': { title: 'Veyr 本地证据报告', generated: '生成时间', events: '条原始事件', overview: '本次摘要', sessionOverview: '会话摘要', sessions: '会话', history: '历史会话', turns: '个观测 turn', latest: '最近活动', partial: '部分覆盖', calls: '次关联调用', envelope: '可测调用包络', observedTurn: '观测 turn 时长', terminalObserved: '已观察到结束', terminalMissing: '未观察到结束', conclusion: '本次结论', suggestions: '建议下一步', timeline: '工具调用时间线', turnEvidence: 'Turn 证据', mcp: '观察到的 MCP 调用', skill: 'Skill Doctor', evidence: '原始证据', noCalls: '本次未观察到可关联的工具调用。', noMcp: '本次未观察到规范 MCP 名称的调用。', time: '开始时间', tool: '工具', result: '结果', duration: '调用包络耗时', source: '测量来源', evidenceCount: '证据事件', unknown: '结果未知', knownSuccess: '已知成功', knownFailure: '已知失败', hookEnvelope: 'Codex hook 时间戳', unavailable: '不可测', mcpColumns: ['MCP Server', '工具', '调用数', '已知成功', '已知失败', '未知', '包络耗时'] as const, boundaryTitle: '解释边界', boundary: '观测 turn 时长从 UserPromptSubmit 到 Stop/SessionEnd 的 hook 时间戳计算；调用包络耗时包含 hook 调度与本地开销，两者均不等同于服务端执行耗时。观察到不等于执行成功；相关不等于因果；数据缺失时保持未知。', skillEvidence: '静态成本为 SKILL.md 字节体积估算，不等于实际注入或账单 token；当前环境未提供可按单个 Skill 归因的原生 usage。' },
  en: { title: 'Veyr local evidence report', generated: 'Generated', events: 'raw event(s)', overview: 'Run summary', sessionOverview: 'Session summary', sessions: 'sessions', history: 'Historical sessions', turns: 'observed turn(s)', latest: 'most recent activity', partial: 'partial coverage', calls: 'correlated call(s)', envelope: 'measured call envelope', observedTurn: 'observed turn elapsed', terminalObserved: 'terminal event observed', terminalMissing: 'terminal event not observed', conclusion: 'What happened', suggestions: 'Recommended next steps', timeline: 'Tool-call timeline', turnEvidence: 'Turn evidence', mcp: 'Observed MCP calls', skill: 'Skill Doctor', evidence: 'Raw evidence', noCalls: 'No correlatable tool calls were observed.', noMcp: 'No calls with canonical MCP names were observed.', time: 'Started', tool: 'Tool', result: 'Outcome', duration: 'Call envelope', source: 'Measurement source', evidenceCount: 'Evidence events', unknown: 'Outcome unknown', knownSuccess: 'Known success', knownFailure: 'Known failure', hookEnvelope: 'Codex hook timestamps', unavailable: 'Unavailable', mcpColumns: ['MCP server', 'Tool', 'Calls', 'Known success', 'Known failure', 'Unknown', 'Envelope'] as const, boundaryTitle: 'Interpretation boundary', boundary: 'Observed turn elapsed is measured between UserPromptSubmit and Stop/SessionEnd hooks. Call envelope time includes hook scheduling and local overhead; neither is server execution time. Observation is not success. Correlation is not causation. Missing data remains unknown.', skillEvidence: 'Static cost is estimated from SKILL.md bytes, not actual injection or billed tokens; this environment does not provide native per-Skill usage attribution.' },
} as const;

function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character); }
function formatMs(value: number | undefined, language: ReportLanguage): string { return value === undefined ? copy[language].unavailable : `${value} ms`; }
function resultLabel(call: ToolCall, language: ReportLanguage): string { return call.status === 'succeeded' ? copy[language].knownSuccess : call.status === 'failed' ? copy[language].knownFailure : copy[language].unknown; }

function sessionHtml(session: SessionSummary, language: ReportLanguage, current = true): string {
  const text = copy[language];
  const calls = session.calls.length ? session.calls.map((call) => `<tr><td>${escapeHtml(call.startedAt ?? call.completedAt ?? '—')}</td><td><code>${escapeHtml(call.toolName)}</code></td><td>${resultLabel(call, language)}</td><td>${formatMs(call.durationMs, language)}</td><td>${call.durationSource === 'hook_envelope' ? text.hookEnvelope : text.unavailable}</td><td>${call.evidenceIds.length}</td></tr>`).join('') : `<tr><td colspan="6">${text.noCalls}</td></tr>`;
  const mcp = session.mcp.length ? session.mcp.map((entry: McpSummary) => `<tr><td>${escapeHtml(entry.server)}</td><td>${escapeHtml(entry.tool)}</td><td>${entry.calls}</td><td>${entry.knownSucceeded}</td><td>${entry.knownFailed}</td><td>${entry.unknown}</td><td>${formatMs(entry.totalEnvelopeMs || undefined, language)}</td></tr>`).join('') : `<tr><td colspan="7">${text.noMcp}</td></tr>`;
  const conclusion = session.calls.length ? `${session.calls.length} ${text.calls} ${language === 'zh-CN' ? '已由 PreToolUse / PostToolUse 关联。' : 'were correlated from PreToolUse / PostToolUse.'}` : text.noCalls;
  const turns = session.turns.map((turn) => `<tr><td><code>${escapeHtml(turn.taskId ?? 'lifecycle')}</code></td><td>${escapeHtml(turn.lastObservedAt)}</td><td>${turn.observedEvents}</td><td>${turn.calls.length}</td><td>${formatMs(turn.observedElapsedMs, language)}</td><td>${turn.terminalObserved ? text.terminalObserved : text.terminalMissing}</td></tr>`).join('');
  return `<section class="hero"><div><span class="badge">${text.partial}</span><h2>${current ? text.overview : text.sessionOverview}</h2><p>${session.observedEvents} ${text.events} · ${session.turns.length} ${text.turns} · ${session.calls.length} ${text.calls} · ${text.envelope}: ${formatMs(session.totalEnvelopeMs || undefined, language)}</p><p>${text.latest}: ${escapeHtml(session.lastObservedAt)}</p></div><div class="session">session<br/><code>${escapeHtml(session.sessionId)}</code></div></section><section><h2>${text.conclusion}</h2><p>${conclusion}</p><h3>${text.suggestions}</h3><ol>${session.suggestions.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ol></section><section><h2>${text.timeline}</h2><table><thead><tr><th>${text.time}</th><th>${text.tool}</th><th>${text.result}</th><th>${text.duration}</th><th>${text.source}</th><th>${text.evidenceCount}</th></tr></thead><tbody>${calls}</tbody></table></section><section><h2>${text.turnEvidence}</h2><table><thead><tr><th>Turn</th><th>${text.latest}</th><th>${text.events}</th><th>${text.calls}</th><th>${text.observedTurn}</th><th>${text.result}</th></tr></thead><tbody>${turns}</tbody></table></section><section><h2>${text.mcp}</h2><table><thead><tr>${text.mcpColumns.map((column) => `<th>${column}</th>`).join('')}</tr></thead><tbody>${mcp}</tbody></table></section>`;
}

function skillDoctorHtml(doctor: SkillDoctorSummary, language: ReportLanguage): string {
  const text = copy[language];
  const row = (skill: SkillDoctorSummary['skills'][number]) => {
    const evidence = skill.evidence === 'injected' ? (language === 'zh-CN' ? '已观察注入' : 'injected observed') : skill.evidence === 'explicit_request' ? 'explicit request' : language === 'zh-CN' ? '本窗口未观测' : 'unobserved in window';
    const usage = skill.nativeTurnUsage ? `${skill.nativeTurnUsage.inputTokens} in / ${skill.nativeTurnUsage.outputTokens} out` : '—';
    const estimatedTokens = (value: number) => language === 'zh-CN' ? `约 ${value} tokens` : `~${value} tokens`;
    return `<tr><td><code>${escapeHtml(skill.name)}</code></td><td>${escapeHtml(skill.source)}</td><td>${estimatedTokens(skill.listingEstimatedTokens)}</td><td>${estimatedTokens(skill.bodyEstimatedTokens)}</td><td>${skill.explicitRequests}</td><td>${skill.injectedCount}</td><td>${skill.lastRequestedAt ?? '—'}</td><td>${evidence}</td><td>${usage}</td><td>${skill.duplicateSources.join(', ') || '—'}</td></tr>`;
  };
  const active = doctor.skills.filter((skill) => skill.evidence !== 'unobserved');
  const inactive = doctor.skills.filter((skill) => skill.evidence === 'unobserved');
  const activeRows = active.map(row).join('') || `<tr><td colspan="10">${language === 'zh-CN' ? '本报告窗口未观察到明确请求或实际注入的 Skill。' : 'No explicit requests or observed injections in this report window.'}</td></tr>`;
  const inactiveRows = inactive.map(row).join('') || `<tr><td colspan="10">—</td></tr>`;
  const summary = language === 'zh-CN'
    ? `${doctor.skills.length} 个可见 Skill · ${doctor.totalListingEstimatedTokens} listing 估算 token · ${doctor.unobservedCount} 个本窗口未观测`
    : `${doctor.skills.length} visible skills · ${doctor.totalListingEstimatedTokens} estimated listing tokens · ${doctor.unobservedCount} unobserved in window`;
  const note = language === 'zh-CN'
    ? 'Listing 成本仅估算名称与 description 的每轮可见成本；激活正文上限不等于实际注入或账单 token；当前环境未提供可按单个 Skill 归因的原生 usage。'
    : 'Listing cost estimates only per-turn visible names and descriptions. Activated body upper bound is not actual injection or billed tokens; this environment does not provide native per-Skill usage attribution.';
  const candidates = inactive.slice(0, 8);
  const estimatedTokens = (value: number) => language === 'zh-CN' ? `约 ${value} tokens` : `~${value} tokens`;
  const candidateRows = candidates.map((skill) => `<tr><td><code>${escapeHtml(skill.name)}</code></td><td>${estimatedTokens(skill.listingEstimatedTokens)}</td><td>${estimatedTokens(skill.bodyEstimatedTokens)}</td><td>${escapeHtml(skill.source)}</td></tr>`).join('') || `<tr><td colspan="4">—</td></tr>`;
  const header = `<thead><tr><th>Skill</th><th>${text.source}</th><th>${language === 'zh-CN' ? 'Listing 成本（约 tokens）' : 'Listing cost (~tokens)'}</th><th>${language === 'zh-CN' ? '激活正文上限（约 tokens）' : 'Activated body upper bound (~tokens)'}</th><th>${language === 'zh-CN' ? '明确请求' : 'Explicit requests'}</th><th>${language === 'zh-CN' ? '已观察注入' : 'Observed injections'}</th><th>${language === 'zh-CN' ? '最近证据' : 'Last evidence'}</th><th>${language === 'zh-CN' ? '证据' : 'Evidence'}</th><th>${language === 'zh-CN' ? '关联 turn usage' : 'Related turn usage'}</th><th>${language === 'zh-CN' ? '重名来源' : 'Duplicate sources'}</th></tr></thead>`;
  return `<section><h2>${text.skill}</h2><p>${summary}</p><h3>${language === 'zh-CN' ? '已请求或已观察注入' : 'Requested or observed injected'}</h3><table>${header}<tbody>${activeRows}</tbody></table><h3>${text.suggestions}</h3><ol>${doctor.recommendations.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ol><details><summary>${language === 'zh-CN' ? `查看 ${doctor.unobservedCount} 个本窗口未观测 Skill 的优化候选` : `View ${doctor.unobservedCount} unobserved-in-window optimization candidates`}</summary><p>${language === 'zh-CN' ? '按 listing 成本排序：当前窗口未观测请求或注入，不代表历史从未使用。' : 'Sorted by listing cost: not observed in this report window, not necessarily never used.'}</p><table><thead><tr><th>Skill</th><th>${language === 'zh-CN' ? 'Listing 成本（约 tokens）' : 'Listing cost (~tokens)'}</th><th>${language === 'zh-CN' ? '激活正文上限（约 tokens）' : 'Activated body upper bound (~tokens)'}</th><th>${text.source}</th></tr></thead><tbody>${candidateRows}</tbody></table><details><summary>${language === 'zh-CN' ? '查看全部未观测 Skill' : 'View all unobserved skills'}</summary><table>${header}<tbody>${inactiveRows}</tbody></table></details></details><p class="muted">${note} 关联 turn usage 是整个 turn 的原生 usage，不是该 Skill 独占 token。</p></section>`;
}

export function renderHtmlReport(report: ReportData, language: ReportLanguage = 'zh-CN'): string {
  const text = copy[language]; const sessions = projectSessions(report.tasks); const latest = sessions[0]; const history = sessions.slice(1);
  const sessionContent = latest ? `${sessionHtml(latest, language)}${history.length ? `<details><summary>${text.history}（${history.length} ${text.sessions}）</summary>${history.map((session) => `<details><summary><code>${escapeHtml(session.sessionId)}</code> · ${session.turns.length} ${text.turns} · ${session.calls.length} ${text.calls} · ${escapeHtml(session.lastObservedAt)}</summary>${sessionHtml(session, language, false)}</details>`).join('')}</details>` : ''}` : `<section><h2>${text.overview}</h2><p>${text.noCalls}</p></section>`;
  const raw = report.events.map((event) => `<tr><td>${escapeHtml(event.occurredAt)}</td><td>${escapeHtml(event.source)}</td><td>${escapeHtml(event.toolName ?? '—')}</td><td>${escapeHtml(event.callId ?? '—')}</td><td>${escapeHtml(event.status)}</td></tr>`).join('');
  return `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${text.title}</title><style>:root{color-scheme:dark}body{font-family:ui-sans-serif,system-ui;max-width:1180px;margin:36px auto;padding:0 22px;background:#080d1d;color:#e5e7eb}h1{font-size:38px;color:#a5b4fc;margin-bottom:8px}h2{font-size:25px;margin:0 0 14px}h3{font-size:16px;color:#c7d2fe;margin:20px 0 8px}p,li{color:#cbd5e1;line-height:1.6}section{background:#111a31;border:1px solid #263a61;border-radius:16px;padding:24px;margin:18px 0}.hero{display:flex;justify-content:space-between;gap:24px;border-color:#354b7d;background:linear-gradient(135deg,#132147,#10182b)}.badge{display:inline-block;border:1px solid #5372bf;color:#bfdbfe;border-radius:99px;padding:3px 9px;font-size:12px;margin-bottom:10px}.session{font-size:12px;color:#94a3b8;text-align:right;overflow-wrap:anywhere}code{color:#c4b5fd}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;border-bottom:1px solid #263a61;padding:11px 9px;vertical-align:top}th{color:#a5b4fc;font-weight:650}ol{padding-left:20px}details{margin:18px 0;background:#0d1528;border-radius:12px;padding:4px 18px}summary{cursor:pointer;padding:14px 0;color:#c7d2fe;font-weight:650}.muted{color:#94a3b8}@media(max-width:700px){.hero{display:block}.session{text-align:left;margin-top:16px}table{font-size:12px;display:block;overflow-x:auto}}</style></head><body><h1>${text.title}</h1><p class="muted">${text.generated} ${escapeHtml(report.generatedAt)} · ${report.events.length} ${text.events}</p>${sessionContent}${skillDoctorHtml(report.skillDoctor, language)}<details><summary>${text.evidence}</summary><table><thead><tr><th>${text.time}</th><th>Event</th><th>${text.tool}</th><th>Call ID</th><th>${text.result}</th></tr></thead><tbody>${raw}</tbody></table></details><section><h2>${text.boundaryTitle}</h2><p>${text.boundary}</p></section></body></html>`;
}
